#!/bin/bash
echo "Input name of your file"
read filename1
if 
	test -e "$filename1" 
then
	echo "This file is already exisits choose another file name"
	read filename2
	touch $filename2
	subl $filename2
else
	touch $filename1
	subl $filename1
fi